# Generated by Django 5.2.10 on 2026-02-17 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0006_vehicle_sold_date_alter_vehicle_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. End of Year Sale', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('discount_type', models.CharField(choices=[('PERCENT', 'Percentage'), ('FIXED_AMOUNT', 'Fixed Amount')], default='PERCENT', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Discount amount: percentage (e.g. 10.00) or fixed dollar amount (e.g. 500.00)', max_digits=10)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='campaign_banners/')),
                ('is_active', models.BooleanField(default=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('leads_generated', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicles', models.ManyToManyField(blank=True, related_name='campaigns', to='inventory.vehicle')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
