# Generated by Django 6.0 on 2026-01-03 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('PURCHASE', 'Purchase Price'), ('REPAIR', 'Repair & Maintenance'), ('TRANSPORT', 'Transport/Shipping'), ('DETAIL', 'Detailing'), ('OTHER', 'Other')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('vendor', models.CharField(blank=True, max_length=100)),
                ('receipt', models.ImageField(blank=True, null=True, upload_to='receipts/')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='inventory.vehicle')),
            ],
        ),
    ]
