# Generated by Django 5.2.10 on 2026-01-29 23:50

import django.core.validators
import django.db.models.deletion
import financials.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.AddField(
            model_name='expense',
            name='invoice_file',
            field=models.FileField(blank=True, help_text='Upload invoice or receipt (PDF, JPG, PNG)', null=True, upload_to=financials.models.invoice_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'gif'])]),
        ),
        migrations.AddField(
            model_name='expense',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='vendor_name',
            field=models.CharField(blank=True, help_text='Alternative to FK - just enter vendor name', max_length=200),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('PURCHASE_PRICE', 'Purchase Price'), ('TAX', 'Tax & Registration'), ('REPAIR', 'Repair & Maintenance'), ('TRANSPORT', 'Transport/Shipping'), ('INSPECTION', 'Inspection'), ('DETAIL', 'Detailing'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='financials.vendor'),
        ),
    ]
