# Generated by Django 5.2.10 on 2026-01-30 02:48

import django.db.models.deletion
import financials.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0002_vendor_alter_expense_options_expense_invoice_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='is_public',
            field=models.BooleanField(default=False, help_text="If True, this record can be shown to customers (e.g., 'New Tires')"),
        ),
        migrations.AddField(
            model_name='expense',
            name='service_type',
            field=models.CharField(blank=True, choices=[('OIL_CHANGE', 'Oil Change'), ('TIRE_ROTATION', 'Tire Rotation'), ('TIRE_REPLACEMENT', 'Tire Replacement'), ('BRAKE_SERVICE', 'Brake Service'), ('TRANSMISSION', 'Transmission Service'), ('ENGINE_REPAIR', 'Engine Repair'), ('BODY_WORK', 'Body Work'), ('PAINT', 'Paint / Touch-up'), ('ELECTRICAL', 'Electrical'), ('AC_HEATING', 'AC / Heating'), ('SUSPENSION', 'Suspension'), ('EXHAUST', 'Exhaust System'), ('INSPECTION', 'Inspection'), ('DETAILING', 'Detailing'), ('OTHER', 'Other')], help_text='Specific type of service (for REPAIR category)', max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='ExpenseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=financials.models.expense_image_upload_path)),
                ('caption', models.CharField(choices=[('BEFORE', 'Before Repair'), ('AFTER', 'After Repair'), ('DURING', 'During Repair'), ('PARTS', 'Parts / Materials'), ('OTHER', 'Other')], default='OTHER', max_length=50)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='financials.expense')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
