# Generated by Django 5.2.10 on 2026-01-30 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0003_expense_is_public_expense_service_type_expenseimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='is_active',
            field=models.BooleanField(default=True, help_text="Inactive vendors won't appear in dropdown selections"),
        ),
        migrations.AddField(
            model_name='vendor',
            name='rating',
            field=models.PositiveSmallIntegerField(default=3, help_text='Internal rating 1-5 stars for work quality'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='service_category',
            field=models.CharField(choices=[('MECHANIC', 'Mechanic / Repair Shop'), ('BODY_SHOP', 'Body Shop / Paint'), ('TRANSPORTER', 'Transporter / Shipping'), ('DMV_TITLE', 'DMV / Title Services'), ('DETAILING', 'Detailing / Cleaning'), ('PARTS', 'Parts Supplier'), ('OTHER', 'Other')], default='OTHER', help_text='Primary type of service this vendor provides', max_length=20),
        ),
    ]
