# Generated by Django 5.2.10 on 2026-02-13 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0004_vendor_enhancements'),
        ('inventory', '0006_vehicle_sold_date_alter_vehicle_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('PURCHASE_PRICE', 'Purchase Price'), ('TAX', 'Tax & Registration'), ('REPAIR', 'Repair & Maintenance'), ('TRANSPORT', 'Transport/Shipping'), ('INSPECTION', 'Inspection'), ('DETAIL', 'Detailing'), ('RENT', 'Rent / Lease'), ('MARKETING', 'Marketing / Advertising'), ('SALARY', 'Salary / Payroll'), ('UTILITIES', 'Utilities'), ('INSURANCE', 'Insurance'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='inventory.vehicle'),
        ),
    ]
