# Generated by Django 5.2.10 on 2026-02-13 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0005_alter_expense_category_alter_expense_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='is_paid',
            field=models.BooleanField(default=False, help_text='Whether this expense / bill has been paid'),
        ),
        migrations.AddField(
            model_name='expense',
            name='paid_date',
            field=models.DateField(blank=True, help_text='Date the bill was actually paid', null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='account_details',
            field=models.TextField(blank=True, help_text="Bank / account info, e.g. 'Bank: Chase, Acct: ****1234'"),
        ),
        migrations.AddField(
            model_name='vendor',
            name='payment_terms',
            field=models.CharField(choices=[('DUE_ON_RECEIPT', 'Due on Receipt'), ('NET_15', 'Net 15'), ('NET_30', 'Net 30'), ('NET_60', 'Net 60')], default='DUE_ON_RECEIPT', max_length=20),
        ),
        migrations.AddField(
            model_name='vendor',
            name='preferred_payment_method',
            field=models.CharField(choices=[('CHECK', 'Check'), ('WIRE', 'Wire Transfer'), ('ACH', 'ACH'), ('CASH', 'Cash')], default='CHECK', max_length=10),
        ),
        migrations.AddField(
            model_name='vendor',
            name='tax_id',
            field=models.CharField(blank=True, help_text='EIN, SSN, or other tax identification number', max_length=50),
        ),
    ]
