# Generated by Django 5.2.10 on 2026-01-16 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='desired_make',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='desired_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='lead_type',
            field=models.CharField(choices=[('GENERAL_INQUIRY', 'General Inquiry'), ('VEHICLE_REQUEST', 'Vehicle Request')], default='GENERAL_INQUIRY', max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='max_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='preferred_year_max',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='preferred_year_min',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
