# Generated by Django 5.2.10 on 2026-01-17 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_appointment_options_remove_appointment_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='check_in_time',
            field=models.DateTimeField(blank=True, help_text='When customer checked in', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='check_out_time',
            field=models.DateTimeField(blank=True, help_text='When customer checked out', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
