# Generated by Django 5.2.10 on 2026-02-12 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_interaction_task'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='assigned_to',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'SALES'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lead',
            name='lead_type',
            field=models.CharField(choices=[('GENERAL_INQUIRY', 'General Inquiry'), ('VEHICLE_REQUEST', 'Vehicle Request'), ('TEST_DRIVE', 'Test Drive')], default='GENERAL_INQUIRY', max_length=20),
        ),
    ]
