# Generated by Django 5.2.10 on 2026-02-12 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_alter_lead_assigned_to_alter_lead_lead_type'),
        ('inventory', '0006_vehicle_sold_date_alter_vehicle_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreed_price', models.DecimalField(decimal_places=2, help_text='Negotiated sale price (defaults to listing price)', max_digits=12)),
                ('trade_in_allowance', models.DecimalField(decimal_places=2, default=0, help_text='Value of customer trade-in vehicle', max_digits=12)),
                ('cash_down_payment', models.DecimalField(decimal_places=2, default=0, help_text='Cash down payment from customer', max_digits=12)),
                ('doc_fee', models.DecimalField(decimal_places=2, default=499.0, help_text='Documentation / dealer fee', max_digits=8)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=6.25, help_text='Sales tax rate as a percentage (e.g. 6.25)', max_digits=5)),
                ('term_months', models.PositiveIntegerField(default=60, help_text='Loan term in months')),
                ('interest_rate', models.DecimalField(decimal_places=2, default=5.9, help_text='Annual interest rate as a percentage (e.g. 5.9)', max_digits=5)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=10)),
                ('version_name', models.CharField(blank=True, default='Offer #1', help_text='Friendly label (e.g. "Aggressive Discount")', max_length=100)),
                ('customer_signature', models.ImageField(blank=True, help_text='Customer signature image captured on acceptance', null=True, upload_to='signatures/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='crm.lead')),
                ('sales_rep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='inventory.vehicle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
