# Generated by Django 5.2.10 on 2026-02-13 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_deal'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(blank=True, max_length=17)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('mileage', models.PositiveIntegerField()),
                ('condition', models.CharField(choices=[('EXCELLENT', 'Excellent'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor')], default='GOOD', max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('front_photo', models.ImageField(blank=True, null=True, upload_to='trade_in_photos/')),
                ('back_photo', models.ImageField(blank=True, null=True, upload_to='trade_in_photos/')),
                ('interior_photo', models.ImageField(blank=True, null=True, upload_to='trade_in_photos/')),
                ('side_photo', models.ImageField(blank=True, null=True, upload_to='trade_in_photos/')),
                ('offer_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Appraised value offered to customer', max_digits=12, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('OFFERED', 'Offered'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(blank=True, help_text='Auto-linked when customer email matches a lead', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trade_ins', to='crm.lead')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
