# Generated by Django 5.2.10 on 2026-02-17 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_tradein'),
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='source_campaign',
            field=models.ForeignKey(blank=True, help_text='The campaign that generated this lead (auto-set if vehicle is in an active campaign)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='marketing.campaign'),
        ),
    ]
