# Generated by Django 5.2.10 on 2026-03-03 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_lead_source_campaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='lead_type',
            field=models.CharField(choices=[('GENERAL_INQUIRY', 'General Inquiry'), ('VEHICLE_REQUEST', 'Vehicle Request'), ('TEST_DRIVE', 'Test Drive'), ('FINANCING', 'Financing Application')], default='GENERAL_INQUIRY', max_length=20),
        ),
    ]
