# Generated by Django 5.2.10 on 2026-03-08 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_add_financing_lead_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='lead',
            field=models.ForeignKey(blank=True, help_text='Auto-linked lead for CRM tracking', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='crm.lead'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='lead_type',
            field=models.CharField(choices=[('GENERAL_INQUIRY', 'General Inquiry'), ('VEHICLE_REQUEST', 'Vehicle Request'), ('TEST_DRIVE', 'Test Drive'), ('FINANCING', 'Financing Application'), ('TRADE_IN', 'Trade-In Appraisal')], default='GENERAL_INQUIRY', max_length=20),
        ),
    ]
