# Generated by Django 5.2.10 on 2026-04-26 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_add_lead_to_appointment_and_trade_in_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='credit_check_consent',
            field=models.BooleanField(blank=True, default=None, help_text='Whether the applicant consented to a credit check (FINANCING leads only)', null=True),
        ),
    ]
