# Generated by Django 5.2.10 on 2026-01-30 02:06

import django.db.models.deletion
import inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text="Document title (e.g., 'Dyno Test Result')", max_length=200)),
                ('file', models.FileField(help_text='Upload PDF, images, or other documents', upload_to=inventory.models.document_upload_path)),
                ('doc_type', models.CharField(choices=[('INSPECTION', 'Inspection Report'), ('SERVICE_RECORD', 'Service Record'), ('OWNERSHIP', 'Ownership / Title'), ('WARRANTY', 'Warranty Document'), ('CARFAX', 'Carfax / Vehicle History'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('is_public', models.BooleanField(default=False, help_text='If True, this document is visible to public customers. If False, only admins can see it.')),
                ('description', models.TextField(blank=True, help_text='Optional notes about this document')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='inventory.vehicle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
