# Generated by Django 5.2.10 on 2026-01-30 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_vehicledocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='sold_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('ACQUIRED', 'Acquired'), ('PREP', 'In Prep'), ('READY', 'Ready'), ('PENDING', 'Pending'), ('SOLD', 'Sold')], default='ACQUIRED', max_length=20),
        ),
    ]
