# Generated by Django 5.2.10 on 2026-02-21 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_vehicle_sold_date_alter_vehicle_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='promo_video',
            field=models.FileField(blank=True, help_text='MP4 promo video for Instagram Reels / TikTok / Facebook Reels.', null=True, upload_to='vehicle_videos/'),
        ),
    ]
