# Generated by Django 5.2.10 on 2026-03-07 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_vehicle_promo_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='body_style',
            field=models.CharField(blank=True, choices=[('SEDAN', 'Sedan'), ('SUV', 'SUV'), ('HATCHBACK', 'Hatchback'), ('COUPE', 'Coupe'), ('TRUCK', 'Truck'), ('MINIVAN', 'Minivan'), ('WAGON', 'Wagon'), ('CONVERTIBLE', 'Convertible'), ('OTHER', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='doors',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='drivetrain',
            field=models.CharField(blank=True, choices=[('FWD', 'Front-Wheel Drive'), ('RWD', 'Rear-Wheel Drive'), ('AWD', 'All-Wheel Drive'), ('4WD', 'Four-Wheel Drive')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='engine',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(blank=True, choices=[('GASOLINE', 'Gasoline'), ('DIESEL', 'Diesel'), ('ELECTRIC', 'Electric'), ('HYBRID', 'Hybrid'), ('PHEV', 'Plug-in Hybrid'), ('OTHER', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='transmission',
            field=models.CharField(blank=True, choices=[('AUTOMATIC', 'Automatic'), ('MANUAL', 'Manual'), ('CVT', 'CVT'), ('OTHER', 'Other')], max_length=20, null=True),
        ),
    ]
