# Generated by Django 5.2.10 on 2026-03-08 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_vehicle_body_style_vehicle_doors_vehicle_drivetrain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='sold_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
