# Generated by Django 5.2.10 on 2026-03-03 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_add_financing_lead_type'),
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='deal',
            field=models.OneToOneField(blank=True, help_text='The deal this loan originated from (optional for direct financing)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan', to='crm.deal'),
        ),
    ]
