# Generated by Django 5.2.10 on 2026-04-28 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_make_deal_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='admin_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='One-time dealership administration fee added to the financed amount', max_digits=10),
        ),
        migrations.AlterField(
            model_name='loan',
            name='principal_amount',
            field=models.DecimalField(decimal_places=2, help_text='Amount financed (vehicle price portion)', max_digits=12),
        ),
    ]
