# Generated by Django 5.2.10 on 2026-02-19 22:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('FACEBOOK', 'Facebook'), ('INSTAGRAM', 'Instagram')], default='FACEBOOK', max_length=20)),
                ('page_name', models.CharField(max_length=255)),
                ('page_id', models.CharField(help_text='Facebook / Instagram Page ID.', max_length=100, unique=True)),
                ('access_token', models.TextField(help_text='Encrypted long-lived Page Access Token.')),
                ('token_expires_at', models.DateTimeField(blank=True, help_text='Null = token does not expire (common for Page tokens).', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='The dealer who connected this page.', on_delete=django.db.models.deletion.CASCADE, related_name='social_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Social Credential',
                'verbose_name_plural': 'Social Credentials',
                'ordering': ['-connected_at'],
                'unique_together': {('user', 'page_id')},
            },
        ),
    ]
