# Generated by Django 6.0 on 2026-01-14 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealerConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_user_ads', models.BooleanField(default=False, help_text='Allow users to post their own vehicle listings', verbose_name='Enable User Ads')),
                ('enable_ai_description', models.BooleanField(default=True, help_text='Enable AI-powered vehicle description generation', verbose_name='Enable AI Description')),
                ('enable_vin_decoder', models.BooleanField(default=True, help_text='Enable automatic VIN decoding feature', verbose_name='Enable VIN Decoder')),
                ('enable_chat_support', models.BooleanField(default=False, help_text='Enable live chat support widget', verbose_name='Enable Chat Support')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dealer Configuration',
                'verbose_name_plural': 'Dealer Configuration',
            },
        ),
    ]
