# Generated by Django 5.1.1 on 2026-01-14 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_dealerconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('SALES', 'Sales Rep'), ('TECHNICIAN', 'Technician'), ('CUSTOMER', 'Customer')], default='CUSTOMER', max_length=50),
        ),
    ]
