# Generated by Django 5.2.10 on 2026-02-13 07:04

import core.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_phone_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedDocumentLink',
            fields=[
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_path', models.CharField(help_text='Relative path to the file inside MEDIA_ROOT (e.g. vehicle_docs/vehicle_2/report.pdf)', max_length=500)),
                ('expires_at', models.DateTimeField(default=core.models.default_expiry, help_text='Link expires after this timestamp (default 7 days).')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shared Document Link',
                'ordering': ['-created_at'],
            },
        ),
    ]
