# Generated by Django 5.2.10 on 2026-02-17 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_shareddocumentlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('EXPORT', 'Export')], max_length=10)),
                ('target_model', models.CharField(help_text="Model name, e.g. 'Vehicle', 'Lead'", max_length=100)),
                ('target_object_id', models.CharField(blank=True, default='', help_text='Primary key of the affected object', max_length=255)),
                ('target_repr', models.CharField(blank=True, default='', help_text="Human-readable representation, e.g. '2024 Toyota Camry'", max_length=500)),
                ('changes', models.JSONField(blank=True, default=dict, help_text="Field-level diff: {'field': {'old': ..., 'new': ...}}")),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['target_model', 'target_object_id'], name='core_auditl_target__d419bd_idx'), models.Index(fields=['user', 'timestamp'], name='core_auditl_user_id_7b678c_idx'), models.Index(fields=['action'], name='core_auditl_action_d9fb24_idx')],
            },
        ),
    ]
