# Generated by Django 5.2.10 on 2026-02-17 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('PRIVACY_POLICY', 'Privacy Policy'), ('TERMS_CONDITIONS', 'Terms & Conditions'), ('RETURN_POLICY', 'Return Policy')], help_text='Each document type can only exist once.', max_length=30, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True, default='', help_text='HTML or Markdown content for the legal page.')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Legal Document',
                'verbose_name_plural': 'Legal Documents',
                'ordering': ['doc_type'],
            },
        ),
    ]
