# Generated by Django 5.2.10 on 2026-02-17 17:49

from django.db import migrations


INITIAL_DOCS = [
    {
        'doc_type': 'PRIVACY_POLICY',
        'title': 'Privacy Policy',
        'content': '',
    },
    {
        'doc_type': 'TERMS_CONDITIONS',
        'title': 'Terms & Conditions',
        'content': '',
    },
    {
        'doc_type': 'RETURN_POLICY',
        'title': 'Return Policy',
        'content': '',
    },
]


def seed_legal_documents(apps, schema_editor):
    LegalDocument = apps.get_model('core', 'LegalDocument')
    for doc in INITIAL_DOCS:
        LegalDocument.objects.get_or_create(
            doc_type=doc['doc_type'],
            defaults={'title': doc['title'], 'content': doc['content']},
        )


def remove_legal_documents(apps, schema_editor):
    LegalDocument = apps.get_model('core', 'LegalDocument')
    LegalDocument.objects.filter(
        doc_type__in=[d['doc_type'] for d in INITIAL_DOCS]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_legaldocument'),
    ]

    operations = [
        migrations.RunPython(seed_legal_documents, remove_legal_documents),
    ]
