# Generated by Codex on 2026-05-27

import decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealerconfiguration',
            name='default_purchase_tax_rate',
            field=models.DecimalField(
                decimal_places=2,
                default=decimal.Decimal('5.00'),
                help_text='Default tax percentage for purchase costing workflows',
                max_digits=5,
                verbose_name='Default Purchase Tax Rate',
            ),
        ),
        migrations.AddField(
            model_name='dealerconfiguration',
            name='enable_invoice_ocr',
            field=models.BooleanField(
                default=True,
                help_text='Allow admins to scan purchase invoices for suggested cost data',
                verbose_name='Enable Invoice OCR',
            ),
        ),
    ]
